Loaded module: python3/3.6.2
INFO:Segmentron:Using 2 GPUs
INFO:Segmentron:Namespace(config_file='configs/cityscapes_danet_resnet.yaml', device='cuda', distributed=True, input_img='tools/demo_vis.png', local_rank=0, log_iter=10, no_cuda=False, num_gpus=2, opts=[], resume=None, skip_val=False, val_epoch=1)
INFO:Segmentron:{
        "SEED": 1024,
        "TIME_STAMP": "2022-02-17-14-01",
        "ROOT_PATH": "/zhome/f9/4/160189/SegmenTron",
        "PHASE": "train",
        "DATASET": {
                "NAME": "cityscape",
                "MEAN": [
                        0.485,
                        0.456,
                        0.406
                ],
                "STD": [
                        0.229,
                        0.224,
                        0.225
                ],
                "IGNORE_INDEX": -1,
                "WORKERS": 4,
                "MODE": "testval"
        },
        "AUG": {
                "MIRROR": true,
                "BLUR_PROB": 0.0,
                "BLUR_RADIUS": 0.0,
                "COLOR_JITTER": null
        },
        "TRAIN": {
                "EPOCHS": 240,
                "BATCH_SIZE": 8,
                "CROP_SIZE": 768,
                "BASE_SIZE": 1024,
                "MODEL_SAVE_DIR": "/work3/s210203/runs/checkpoints/",
                "LOG_SAVE_DIR": "/work3/s210203/runs/logs/",
                "PRETRAINED_MODEL_PATH": "",
                "BACKBONE_PRETRAINED": true,
                "BACKBONE_PRETRAINED_PATH": "",
                "RESUME_MODEL_PATH": "",
                "SYNC_BATCH_NORM": true,
                "SNAPSHOT_EPOCH": 10
        },
        "SOLVER": {
                "LR": 0.003,
                "OPTIMIZER": "sgd",
                "EPSILON": 1e-08,
                "MOMENTUM": 0.9,
                "WEIGHT_DECAY": 0.0001,
                "DECODER_LR_FACTOR": 10.0,
                "LR_SCHEDULER": "poly",
                "POLY": {
                        "POWER": 0.9
                },
                "STEP": {
                        "GAMMA": 0.1,
                        "DECAY_EPOCH": [
                                10,
                                20
                        ]
                },
                "WARMUP": {
                        "EPOCHS": 0.0,
                        "FACTOR": 0.3333333333333333,
                        "METHOD": "linear"
                },
                "OHEM": false,
                "AUX": false,
                "AUX_WEIGHT": 0.4,
                "LOSS_NAME": ""
        },
        "TEST": {
                "TEST_MODEL_PATH": "",
                "BATCH_SIZE": 1,
                "CROP_SIZE": null,
                "SCALES": [
                        1.0
                ],
                "FLIP": false
        },
        "VISUAL": {
                "OUTPUT_DIR": "/work3/s210203/runs/visual/"
        },
        "MODEL": {
                "MODEL_NAME": "DANet",
                "BACKBONE": "resnet50",
                "BACKBONE_SCALE": 1.0,
                "MULTI_LOSS_WEIGHT": [
                        1.0
                ],
                "DEFAULT_GROUP_NUMBER": 32,
                "DEFAULT_EPSILON": 1e-05,
                "BN_TYPE": "BN",
                "BN_EPS_FOR_ENCODER": null,
                "BN_EPS_FOR_DECODER": null,
                "OUTPUT_STRIDE": 8,
                "BN_MOMENTUM": null,
                "DANET": {
                        "MULTI_DILATION": [
                                4,
                                8,
                                16
                        ],
                        "MULTI_GRID": true
                },
                "CCNET": {
                        "RECURRENCE": 2
                }
        }
}
INFO:Segmentron:Found 2975 images in the folder /zhome/f9/4/160189/SegmenTron/datasets/cityscapes/leftImg8bit/train
INFO:Segmentron:Found 500 images in the folder /zhome/f9/4/160189/SegmenTron/datasets/cityscapes/leftImg8bit/val
INFO:Segmentron:load backbone pretrained model from url..
INFO:Segmentron:<All keys matched successfully>
INFO:Segmentron:DANet flops: 1584.404G input shape is [3, 1024, 2048], params: 47.463M
INFO:Segmentron:SyncBatchNorm is effective!
INFO:Segmentron:Start training, Total Epochs: 240 = Total Iterations 44400
Traceback (most recent call last):
  File "./tools/train.py", line 258, in <module>
    trainer.train()
  File "./tools/train.py", line 160, in train
    losses.backward()
  File "/zhome/f9/4/160189/env_a100/lib/python3.6/site-packages/torch/tensor.py", line 245, in backward
Traceback (most recent call last):
  File "./tools/train.py", line 258, in <module>
    trainer.train()
  File "./tools/train.py", line 160, in train
    losses.backward()
  File "/zhome/f9/4/160189/env_a100/lib/python3.6/site-packages/torch/tensor.py", line 245, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/zhome/f9/4/160189/env_a100/lib/python3.6/site-packages/torch/autograd/__init__.py", line 147, in backward
  File "/zhome/f9/4/160189/env_a100/lib/python3.6/site-packages/torch/autograd/__init__.py", line 147, in backward
    allow_unreachable=True, accumulate_grad=True)  # allow_unreachable flag
    allow_unreachable=True, accumulate_grad=True)  # allow_unreachable flag
RuntimeError: CUDA out of memory. Tried to allocate 2.53 GiB (GPU 0; 39.59 GiB total capacity; 32.11 GiB already allocated; 1.24 GiB free; 36.45 GiB reserved in total by PyTorch)
RuntimeError: CUDA out of memory. Tried to allocate 2.53 GiB (GPU 1; 39.59 GiB total capacity; 31.92 GiB already allocated; 1.49 GiB free; 36.20 GiB reserved in total by PyTorch)
Traceback (most recent call last):
  File "/appl/python/3.6.2/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/appl/python/3.6.2/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/zhome/f9/4/160189/env_a100/lib/python3.6/site-packages/torch/distributed/launch.py", line 340, in <module>
    main()
  File "/zhome/f9/4/160189/env_a100/lib/python3.6/site-packages/torch/distributed/launch.py", line 326, in main
    sigkill_handler(signal.SIGTERM, None)  # not coming back
  File "/zhome/f9/4/160189/env_a100/lib/python3.6/site-packages/torch/distributed/launch.py", line 301, in sigkill_handler
    raise subprocess.CalledProcessError(returncode=last_return_code, cmd=cmd)
subprocess.CalledProcessError: Command '['/zhome/f9/4/160189/env_a100/bin/python', '-u', './tools/train.py', '--local_rank=1', '--config-file', 'configs/cityscapes_danet_resnet.yaml']' returned non-zero exit status 1.
